### ISSUE TITLE
Can I start app with .env file?

### ISSUE THREAD

**Issue by mcauto** [microsoft/vscode-spring-boot-dashboard#70]
Hello! I love this plugin!

I want to use environment variables with spring boot dashboard.

ex) [Jetbrain - EnvFile](https://plugins.jetbrains.com/plugin/7861-envfile)

### application.yml
```yaml
spring:
  profiles: local
  datasource:
    url: >
      jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DATABASE_NAME}?
      autoReconnect=true&
      useSSL=false&
      useUnicode=true&
      characterEncoding=utf8&
      serverTimezone=UTC
    username: ${MYSQL_DATABASE_USERNAME}
    password: ${MYSQL_DATABASE_PASSWORD}
```

### ./mysql/.env
```bash
MYSQL_ROOT_PASSWORD=password
MYSQL_DATABASE=database
MYSQL_USER=user
MYSQL_PASSWORD=password
MYSQL_PORT=13306
```

Thank you!
